"""Add details and payment_method to Spending

Revision ID: 5b7af72d0a3e
Revises: 
Create Date: 2024-11-13 14:39:35.214376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b7af72d0a3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spending', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spending', schema=None) as batch_op:
        batch_op.drop_column('payment_method')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
