"""empty message

Revision ID: 5d4963cad7d4
Revises: 5b7af72d0a3e
Create Date: 2024-11-21 12:17:05.460316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d4963cad7d4'
down_revision = '5b7af72d0a3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    op.drop_table('transaction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('dcid', sa.INTEGER(), nullable=False),
    sa.Column('thali_number', sa.VARCHAR(), nullable=False),
    sa.Column('total_amount', sa.FLOAT(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['thali_number'], ['person.thali_number'], ),
    sa.PrimaryKeyConstraint('dcid')
    )
    op.create_table('person',
    sa.Column('thali_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('thali_number'),
    sa.UniqueConstraint('thali_number')
    )
    # ### end Alembic commands ###
